- name: Install bridge-utils package
  ansible.builtin.package:
    name: bridge-utils
    state: present

- name: Get enp* interface name
  ansible.builtin.shell: "ip -o link show | awk -F': ' '/enp/{print $2}' | head -n 1"
  register: enp_interface

- name: Check if bridge interface exists
  ansible.builtin.command: ip link show br0
  register: bridge_check
  ignore_errors: yes

- name: Create bridge interface if not exists
  ansible.builtin.command: ip link add name br0 type bridge
  when: bridge_check.rc != 0

- name: Check if enp* interface is part of bridge
  ansible.builtin.command: ip link show master br0
  register: bridge_members
  ignore_errors: yes

- name: Add enp* interface to bridge if not already a member
  ansible.builtin.shell: ip link set "{{ enp_interface.stdout }}" master br0
  when: enp_interface.stdout not in bridge_members.stdout

- name: Bring up bridge interface
  ansible.builtin.command: ip link set br0 up

- name: Bring up enp* interface
  ansible.builtin.command: ip link set {{ enp_interface.stdout }} up