---
- name: Remove old Docker versions
  ansible.builtin.apt:
    name: docker,docker-client,docker-client-latest,docker-common,docker-latest,docker-latest-logrotate,docker-logrotate,docker-engine
    state: absent
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present
- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce,docker-ce-cli,containerd.io,docker-compose-plugin,docker-compose,python3-pip
    state: present
- name: Add ubuntu to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
- name: Start Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes