- name: Install NetworkManager
  ansible.builtin.apt:
    name: network-manager
    state: present
- name: Download Flannel binary
  ansible.builtin.get_url:
    url: https://github.com/flannel-io/flannel/releases/download/v0.25.3/flanneld-amd64
    dest: /usr/local/bin/flanneld
    mode: '0755'
- name: Create Flannel directory
  ansible.builtin.file:
    path: /etc/flannel
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Create Flannel configuration
  copy:
    dest: /etc/flannel/net-conf.json
    content: |
      {
        "Network": "10.244.0.0/16",
        "Backend": {
          "Type": "vxlan"
        }
      }
- name: Create Flannel service file
  ansible.builtin.copy:
    dest: /etc/systemd/system/flanneld.service
    content: |
      [Unit]
      Description=Flannel
      After=network.target
      Before=docker.service

      [Service]
      ExecStart=/usr/local/bin/flanneld --etcd-endpoints=http://master.govno.cloud:2379 --iface=enp0s25
      ExecReload=/bin/kill -HUP $MAINPID
      Restart=on-failure
      Type=notify

      [Install]
      WantedBy=multi-user.target
  notify: reload and restart flanneld