version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.2.4
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_DEBUG: "false"
  master:
    image: loqutus/govnocloud-master
    ports:
      - "7070:7070"
    environment:
      "MASTER_ETCD_HOST": "etcd"
      "MASTER_NODES": "x220:x220.rusik69.lol:6969,x230:x230.rusik69.lol:6969"
    depends_on:
      - etcd
  front:
    image: loqutus/govnocloud-front
    ports:
      - "8080:80"
    depends_on:
      - master