version: '3'
services:
  node:
    image: loqutus/govnocloud-node
    ports:
      - "100.125.175.107:6969:6969"
    environment:
      "NODE_LIBVIRT_SOCKET" : "qemu:///system"
      "NODE_NAME": "x220"
      "NODE_IP": "100.125.175.107"
      "NODE_LISTEN_HOST": "0.0.0.0"
    volumes:
      - /run/libvirt:/run/libvirt/
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/libvirt/images:/var/lib/libvirt/images
      - /mnt:/mnt