FROM golang:1.21-alpine AS build-env
WORKDIR /go/src/github.com/rusik69/govnocloud
COPY . ./
RUN apk add --no-cache libvirt-dev make bash gcc
RUN make
FROM alpine:latest
WORKDIR /app
COPY --from=build-env /go/src/github.com/rusik69/govnocloud/bin/govnocloud /app/
ENTRYPOINT ["/app/govnocloud", "node"]
EXPOSE 6969