---
- name: install packages
  ansible.builtin.apt:
    name: 
      - git
      - build-essential
      - golang
      - libvirt-dev
      - ca-certificates
- name: copy cleanup script
  ansible.builtin.copy:
    src: cleanup.sh
    dest: /usr/local/bin/cleanup.sh
    mode: 0755
- name: Schedule Docker cleanup
  ansible.builtin.cron:
    name: "Docker cleanup"
    user: "root"
    minute: "0"
    hour: "5"
    job: "/usr/bin/docker system prune -f > /dev/null 2>&1"
