- name: Install git
  ansible.builtin.dnf:
    name: git
    state: present
- name: Schedule Docker cleanup
  ansible.builtin.cron:
    name: "Docker cleanup"
    user: "root"
    minute: "0"
    hour: "5"
    job: "/usr/bin/docker system prune -f > /dev/null 2>&1"