- name: Install packages
  ansible.builtin.apt:
    name: ca-certificates,guestfs-tools,cloud-utils,genisoimage
    state: present
- name: install govnocloud-master service
  ansible.builtin.template:
    src: govnocloud-master.service.j2
    dest: /etc/systemd/system/govnocloud-master.service
    mode: 0644
  register: govnocloud_master_service
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: govnocloud_master_service.changed
- name: include ceph tasks
  include_tasks: ceph.yml
- name: include prometheus tasks
  include_tasks: prometheus.yml
- name: include grafana
  include_tasks: grafana.yml