- name: Add PPA
  ansible.builtin.apt_repository:
    repo: ppa:james-page/caracal
    state: present
- name: Install packages
  ansible.builtin.apt:
    name: ca-certificates,guestfs-tools,cloud-utils,genisoimage,etcd-server,cephadm
    state: present
- name: install govnocloud-master service
  ansible.builtin.template:
    src: govnocloud-master.service.j2
    dest: /etc/systemd/system/govnocloud-master.service
    mode: 0644
  register: govnocloud_master_service
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: govnocloud_master_service.changed
- name: start etcd
  ansible.builtin.systemd:
    name: etcd
    state: started
    enabled: yes
- name: Check if /etc/ceph/ceph.conf exists
  ansible.builtin.stat:
    path: /etc/ceph/ceph.conf
  register: ceph_conf
- name: bootstrap ceph
  ansible.builtin.shell: |
    cephadm bootstrap --mon-ip {{ ansible_enp0s31f6.ipv4.address }}
  when: not ceph_conf.stat.exists