- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Ensure Prometheus service is started and enabled
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes