---
- name: Run common role on all hosts
  hosts: all
  roles:
    - common
- name: Run master role on master hosts
  hosts: masters
  roles:
    - master
- name: Run node role on node hosts
  hosts: nodes
  roles:
    - node
- name: Run osd role on osd hosts
  hosts: osds
  roles:
    - osd