---
- name: Install packages
  ansible.builtin.dnf:
    name: libvirt,qemu-kvm,python3-devel,libxml2-devel,libxslt-devel,redhat-rpm-config,gcc,libguestfs-tools,genisoimage,guestfs-tools,ansible,bridge-utils
    state: present
- name: Install lxml
  ansible.builtin.pip:
    name: lxml
    state: present
- name: Start libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
- name: copy cleanup script
  ansible.builtin.copy:
    src: cleanup.sh
    dest: /usr/local/bin/cleanup.sh
    mode: 0755
- name: copy get_logs.sh
  ansible.builtin.copy:
    src: get_logs.sh
    dest: /usr/local/bin/get_logs.sh
    mode: 0755
- name: Create default storage pool
  community.libvirt.virt_pool:
    name: default
    state: present
    xml: |
      <pool type='dir'>
        <name>default</name>
        <target>
          <path>/var/lib/libvirt/images</path>
        </target>
      </pool>
- name: add ssh key to root
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600
- name: install govnocloud-node service
  ansible.builtin.template:
    src: govnocloud-node.service.j2
    dest: /etc/systemd/system/govnocloud-node.service
    mode: 0644
  register: govnocloud_node_service
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: govnocloud_node_service.changed
- name: create govnocloud directory
  ansible.builtin.file:
    path: /etc/govnocloud
    state: directory
    owner: root
    group: root
    mode: 0600
- name: create tailscale token file
  ansible.builtin.template:
    src: tailscale_auth_key.j2
    dest: /etc/govnocloud/tailscale_auth_key
    owner: root
    group: root
    mode: 0600
- name: copy ansible to /etc/govnocloud
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../ansible"
    dest: /etc/govnocloud/
    owner: root
    group: root
    mode: 0600