---
- name: Install packages
  ansible.builtin.apt:
    name: qemu-kvm,python3-dev,python3-lxml,libxml2-dev,libxslt-dev,gcc,libguestfs-tools,genisoimage,guestfs-tools,ansible,bridge-utils,libvirt-daemon-system,libvirt-clients,libvirt-dev,python3-libvirt
    state: present
- name: Start libvirtd
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: yes
- name: copy cleanup script
  ansible.builtin.copy:
    src: cleanup.sh
    dest: /usr/local/bin/cleanup.sh
    mode: 0755
- name: copy get_logs.sh
  ansible.builtin.copy:
    src: get_logs.sh
    dest: /usr/local/bin/get_logs.sh
    mode: 0755
- name: Create default storage pool
  community.libvirt.virt_pool:
    name: default
    state: present
    xml: |
      <pool type='dir'>
        <name>default</name>
        <target>
          <path>/var/lib/libvirt/images</path>
        </target>
      </pool>

- name: Create bridge connection
  community.general.nmcli:
    conn_name: bridge0
    ifname: bridge0
    state: present
    type: bridge
    autoconnect: yes

- name: Add 'enp0s25' to the bridge
  community.general.nmcli:
    conn_name: bridge-slave-enp0s25
    ifname: enp0s25
    state: present
    type: bridge-slave
    master: bridge0

- name: Define a new libvirt network
  community.libvirt.virt_net:
    command: define
    name: br0
    xml: |
      <network>
        <name>bridge0</name>
        <forward mode='bridge'/>
        <bridge name='bridge0'/>
      </network>

- name: install govnocloud-node service
  ansible.builtin.template:
    src: govnocloud-node.service.j2
    dest: /etc/systemd/system/govnocloud-node.service
    mode: 0644
  register: govnocloud_node_service
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: govnocloud_node_service.changed
- name: create govnocloud directory
  ansible.builtin.file:
    path: /etc/govnocloud
    state: directory
    owner: root
    group: root
    mode: 0600
- name: copy ansible to /etc/govnocloud
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../ansible"
    dest: /etc/govnocloud/
    owner: root
    group: root
    mode: 0600