---
- name: wait for connection
  ansible.builtin.wait_for_connection:
    timeout: 60
- name: configure dhcp networking on ubuntu 22.04
  ansible.builtin.copy:
    src: 01-enp0s3.yaml
    dest: /etc/netplan/01-enp0s3.yaml
    owner: root
    group: root
    mode: 0644
  notify: netplan apply
- name: Flush handlers
  meta: flush_handlers
- name: Add Tailscale GPG key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    state: present
- name: Add Tailscale repo
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main
    state: present
- name: Update apt and install Tailscale
  apt:
    name: tailscale
    update_cache: yes
    state: present
- name: Authenticate Tailscale
  command: tailscale up --authkey {{ tailscale_authkey }}