on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ansible
      run: make ansible
    - name: build
      run: make get build
    - name: deploy
      run: make deploy
    - name: composetest
      run: make composetest
    - name: logs
      run: make logs
      if: always()
    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   with:
    #     tag_name: v0.0.1
    #     release_name: Release v0.0.1
    #     draft: false
    #     prerelease: false

    # - name: Upload binary
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./bin/govnocloud-linux-amd64
    #     asset_name: govnocloud-linux-amd64
    #     asset_content_type: application/octet-stream
    timeout-minutes: 30